apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      # exclude heavy kinds — but do NOT list Endpoints or EndpointSlice here
      - Lease
      - TokenReview
      - SelfSubjectAccessReview
