Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"


  config.vm.define "niboukhaS" do |control| # control is like a local configuration object specific to that VM
    control.vm.hostname = "niboukhaS"
    control.vm.network "private_network", ip: "192.168.56.110"

    control.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--name", "niboukhaS"]
    end

    control.vm.provision "shell", path: "./scripts/server.sh"
  
  end

  config.vm.define "niboukhaWS" do |control|
    control.vm.hostname = "niboukhaWS"
    control.vm.network "private_network", ip: "192.168.56.111"

    control.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--name", "niboukhaWS"]
    end

    control.vm.provision "shell", path: "./scripts/workerServer.sh"
  
  end

end
