Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # gives passwordless SSH between VMs
  config.ssh.insert_key = false

  # Shared folder so server and worker can exchange token
  config.vm.synced_folder ".", "/vagrant"

  # --- Master VM ---
  config.vm.define "gkaribS" do |server|
    server.vm.hostname = "gkaribS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024 # 512
      vb.cpus = 1
      vb.name = "gkaribS"
    end
    server.vm.provision "shell", path: "./scripts/MasterSetup.sh"
  end

  # --- Worker Server VM ---
  config.vm.define "gkaribSW" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.hostname = "gkaribSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
    vb.memory = 1024 # 512
      vb.cpus = 1
      vb.name = "gkaribSW"
    end
    worker.vm.provision "shell", path: "./scripts/WorkerSetup.sh"
  end

end
