Vagrant.configure("2") do |config|
    
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.hostname = "bonus"
    config.vm.network "private_network", ip: "192.168.56.10"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--name", "bonus"]
    end

    config.vm.provision "shell", path: "./scripts/bonus.sh"

end